# Numpy

In [1]:
import numpy as np
#Generate a 2D array of random integers 
B = np.random.randint(2, 10,(3, 3));   A = B//2
print(f'A = \n {A} \n'); print(f'B = \n {B} \n')
print(f'Dot:\n {A@B}\n')
x = np.round(B/A)
print(f'Hadamard Mul:\n {A*B} \n'); print(f'Hadamard Div (rounded):\n {x}\n')
print(f'Transpose of A:\n {A.T}\n')
print(f'Adding 10 to every element:\n {A.T + 10}\n')
print(f'Mutiply by pi:\n {A*np.pi}\n')
print(f'Sin:\n {np.sin(A)}\n')

A = 
 [[1 1 1]
 [2 4 3]
 [1 2 1]] 

B = 
 [[2 3 3]
 [4 9 6]
 [3 5 3]] 

Dot:
 [[ 9 17 12]
 [29 57 39]
 [13 26 18]]

Hadamard Mul:
 [[ 2  3  3]
 [ 8 36 18]
 [ 3 10  3]] 

Hadamard Div (rounded):
 [[2. 3. 3.]
 [2. 2. 2.]
 [3. 2. 3.]]

Transpose of A:
 [[1 2 1]
 [1 4 2]
 [1 3 1]]

Adding 10 to every element:
 [[11 12 11]
 [11 14 12]
 [11 13 11]]

Mutiply by pi:
 [[ 3.14159265  3.14159265  3.14159265]
 [ 6.28318531 12.56637061  9.42477796]
 [ 3.14159265  6.28318531  3.14159265]]

Sin:
 [[ 0.84147098  0.84147098  0.84147098]
 [ 0.90929743 -0.7568025   0.14112001]
 [ 0.84147098  0.90929743  0.84147098]]



In [14]:
arr = np.array(range(1,5))
print(arr)

[1 2 3 4]


In [5]:
arr2d = np.array( [ [1,2,3], [3,4,5] , [5,6,7] ] ); print(arr2d)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [6]:
print(np.array([1,2,3, False]))

[1 2 3 0]


In [10]:
print(np.array([1,2,3, '5', 6.0]))

['1' '2' '3' '5' '6.0']


In [8]:
print(np.array([1,2,3, 5.0]))

[1. 2. 3. 5.]


---

In [15]:
arr.shape

(4,)

In [17]:
print(
    np.array([
        [1,2,3],
        [1,2,3]
    ])
)

[[1 2 3]
 [1 2 3]]


In [19]:
arr.size

4

In [20]:
arr2d.size

9

## Ops on array

In [21]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [27]:
arr = np.arange(8)
reshaped=arr.reshape(2,4)
print(reshaped)

[[0 1 2 3]
 [4 5 6 7]]


In [28]:
r1 = np.array([1,2,3,4])
r2 = np.array([4,3,2,1])

print(r1+r2)

[5 5 5 5]


In [38]:
print(r1,r1 + (4,4,4,4))

[1 2 3 4] [5 6 7 8]


In [40]:
print(r1 + (5,0,0,0))

[6 2 3 4]


In [42]:
print( r1@r2 )

20


## Concatenation

In [53]:
arr1 = np.array( [[1,2],[3,4]] )
arr2 = np.array( [[5,6]] )
print(arr1.shape, arr2.shape)

(2, 2) (1, 2)


In [54]:
con= np.concatenate( (arr1,arr2), axis=0 )
print(con)

[[1 2]
 [3 4]
 [5 6]]


In [55]:
x=slice(0,0)
print(arr1[x])

[]


In [56]:
a = np.arange(36)
r= a.reshape(6,6)
print(r)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [58]:
r[0,3:6]

array([3, 4, 5])

In [67]:
r[-2:, -2:]

array([[28, 29],
       [34, 35]])

---

# Pandas

In [22]:
import modin.pandas as pd

In [23]:
pd.Series([1,2,3], name='index')

0    1
1    2
2    3
Name: index, dtype: int64

In [24]:
import seaborn as sns

In [25]:
df = sns.load_dataset('titanic')

In [26]:
df.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [27]:
df.info

<bound method DataFrame.info of      survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_m

In [28]:
df.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [30]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [32]:
agesex=df[['age','sex']]; agesex

age     sex
0    22.0    male
1    38.0  female
2    26.0  female
3    35.0  female
4    35.0    male
..    ...     ...
886  27.0    male
887  19.0  female
888   NaN  female
889  26.0    male
890  32.0    male

[891 rows x 2 columns]

## Filter